import type { Recipe } from "./types";

export const RECIPES: Recipe[] = [
  {
    id: "plov",
    name: "Плов по-алматински",
    description: "Классический плов с бараниной — любимое блюдо всей семьи",
    categories: ["family-favorites", "kazakh", "indulge"],
    diets: ["none", "gluten-free", "low-carb"],
    prepTime: 20,
    cookTime: 60,
    servings: 5,
    calories: 520,
    familyFavorite: true,
    tags: ["мясо", "рис", "выходные"],
    ingredients: [
      { name: "Баранина", amount: "800 г", magnumSearch: "баранина" },
      { name: "Рис", amount: "500 г", magnumSearch: "рис" },
      { name: "Морковь", amount: "400 г", magnumSearch: "морковь" },
      { name: "Лук репчатый", amount: "3 шт", magnumSearch: "лук" },
      { name: "Масло растительное", amount: "100 мл", magnumSearch: "масло растительное" },
      { name: "Чеснок", amount: "1 головка", magnumSearch: "чеснок" },
      { name: "Зира", amount: "1 ч.л.", magnumSearch: "зира" },
      { name: "Соль", amount: "по вкусу", magnumSearch: "соль" },
    ],
    steps: [
      "Нарезать мясо кубиками, обжарить на сильном огне до золотистой корочки",
      "Добавить нарезанный лук, жарить 5 минут",
      "Добавить нарезанную соломкой морковь, тушить 15 минут",
      "Залить водой, добавить рис, зиру и соль",
      "Тушить на медленном огне 40 минут под крышкой",
      "В конце добавить целую головку чеснока",
      "Дать настояться 15 минут перед подачей",
    ],
  },
  {
    id: "beshbarmak",
    name: "Бешбармак",
    description: "Традиционное казахское блюдо — лапша с отварным мясом",
    categories: ["kazakh", "family-favorites", "indulge"],
    diets: ["none"],
    prepTime: 30,
    cookTime: 120,
    servings: 5,
    calories: 580,
    familyFavorite: true,
    tags: ["мясо", "традиция", "праздник"],
    ingredients: [
      { name: "Говядина на кости", amount: "1 кг", magnumSearch: "говядина" },
      { name: "Лук репчатый", amount: "4 шт", magnumSearch: "лук" },
      { name: "Яйца", amount: "3 шт", magnumSearch: "яйца" },
      { name: "Мука", amount: "500 г", magnumSearch: "мука" },
      { name: "Соль", amount: "по вкусу", magnumSearch: "соль" },
      { name: "Перец чёрный", amount: "по вкусу", magnumSearch: "перец" },
      { name: "Укроп", amount: "пучок", magnumSearch: "укроп" },
    ],
    steps: [
      "Варить мясо 1.5-2 часа до готовности",
      "Приготовить тесто из муки, яиц и соли, раскатать тонко",
      "Нарезать тесто на широкие полоски",
      "Отварить лапшу в бульоне 5-7 минут",
      "Нарезать мясо, выложить на лапшу",
      "Подавать с нарезанным луком и зеленью",
    ],
  },
  {
    id: "chicken-cutlets",
    name: "Куриные котлеты",
    description: "Нежные котлеты — любимое блюдо Данила и Леры",
    categories: ["kids", "family-favorites", "quick"],
    diets: ["none", "gluten-free", "low-carb"],
    prepTime: 15,
    cookTime: 25,
    servings: 5,
    calories: 320,
    familyFavorite: true,
    tags: ["курица", "дети", "будни"],
    ingredients: [
      { name: "Куриный фарш", amount: "800 г", magnumSearch: "куриный фарш" },
      { name: "Лук репчатый", amount: "1 шт", magnumSearch: "лук" },
      { name: "Яйцо", amount: "1 шт", magnumSearch: "яйца" },
      { name: "Сухари панировочные", amount: "100 г", magnumSearch: "сухари" },
      { name: "Соль", amount: "по вкусу", magnumSearch: "соль" },
      { name: "Масло растительное", amount: "50 мл", magnumSearch: "масло растительное" },
    ],
    steps: [
      "Смешать фарш с мелко нарезанным луком, яйцом и солью",
      "Сформировать котлеты",
      "Обвалять в сухарях",
      "Жарить на сковороде по 5-7 минут с каждой стороны",
      "Подавать с гарниром",
    ],
  },
  {
    id: "pasta-carbonara",
    name: "Паста Карбонара",
    description: "Быстрая и сытная паста — хит у Славы",
    categories: ["quick", "indulge"],
    diets: ["none"],
    prepTime: 10,
    cookTime: 15,
    servings: 5,
    calories: 480,
    tags: ["паста", "быстро", "сыр"],
    ingredients: [
      { name: "Спагетти", amount: "500 г", magnumSearch: "спагетти" },
      { name: "Бекон", amount: "200 г", magnumSearch: "бекон" },
      { name: "Яйца", amount: "4 шт", magnumSearch: "яйца" },
      { name: "Пarmesan", amount: "100 г", magnumSearch: "parmesan" },
      { name: "Чеснок", amount: "2 зубчика", magnumSearch: "чеснок" },
      { name: "Соль", amount: "по вкусу", magnumSearch: "соль" },
      { name: "Перец чёрный", amount: "по вкусу", magnumSearch: "перец" },
    ],
    steps: [
      "Отварить спагетти al dente",
      "Обжарить бекон до хрустящей корочки",
      "Смешать яйца с тертым сыром",
      "Смешать горячую пасту с беконом и яично-сырной смесью",
      "Подавать сразу с перцем",
    ],
  },
  {
    id: "greek-salad",
    name: "Греческий салат",
    description: "Свежий лёгкий салат для жаркого алматинского лета",
    categories: ["healthy", "low-cal", "quick"],
    diets: ["vegetarian", "gluten-free", "keto", "low-carb"],
    prepTime: 15,
    cookTime: 0,
    servings: 5,
    calories: 180,
    tags: ["салат", "лето", "лёгкое"],
    ingredients: [
      { name: "Помидоры", amount: "4 шт", magnumSearch: "помидоры" },
      { name: "Огурцы", amount: "3 шт", magnumSearch: "огурцы" },
      { name: "Болгарский перец", amount: "2 шт", magnumSearch: "перец болгарский" },
      { name: "Сыр фета", amount: "200 г", magnumSearch: "фета" },
      { name: "Маслины", amount: "100 г", magnumSearch: "маслины" },
      { name: "Оливковое масло", amount: "50 мл", magnumSearch: "оливковое масло" },
      { name: "Лимон", amount: "1 шт", magnumSearch: "лимон" },
    ],
    steps: [
      "Нарезать овощи крупными кубиками",
      "Добавить кубики феты и маслины",
      "Заправить оливковым маслом и лимонным соком",
      "Подавать сразу",
    ],
  },
  {
    id: "pelmeni",
    name: "Пельмени домашние",
    description: "Сытные пельмени — любимое блюдо всей семьи на зиму",
    categories: ["family-favorites", "indulge"],
    diets: ["none"],
    prepTime: 60,
    cookTime: 15,
    servings: 5,
    calories: 420,
    familyFavorite: true,
    tags: ["мясо", "зима", "традиция"],
    ingredients: [
      { name: "Говяжий фарш", amount: "500 г", magnumSearch: "говяжий фарш" },
      { name: "Свиной фарш", amount: "300 г", magnumSearch: "свиной фарш" },
      { name: "Мука", amount: "400 г", magnumSearch: "мука" },
      { name: "Яйца", amount: "2 шт", magnumSearch: "яйца" },
      { name: "Лук репчатый", amount: "2 шт", magnumSearch: "лук" },
      { name: "Сметана", amount: "200 г", magnumSearch: "сметана" },
      { name: "Соль", amount: "по вкусу", magnumSearch: "соль" },
      { name: "Перец", amount: "по вкусу", magnumSearch: "перец" },
    ],
    steps: [
      "Замесить тесто из муки, яйца и воды",
      "Смешать фарш с луком, солью и перцем",
      "Раскатать тесто, вырезать кружки",
      "Начинить фаршем, злепить пельмени",
      "Варить в подсоленной воде 7-10 минут",
      "Подавать со сметаной",
    ],
  },
  {
    id: "fish-baked",
    name: "Запечённая рыба с овощами",
    description: "Полезное блюдо для здорового ужина",
    categories: ["healthy", "low-cal"],
    diets: ["none", "gluten-free", "keto", "low-carb"],
    prepTime: 15,
    cookTime: 35,
    servings: 5,
    calories: 280,
    tags: ["рыба", "здоровое", "лёгкое"],
    ingredients: [
      { name: "Филе судака", amount: "800 г", magnumSearch: "судак" },
      { name: "Кабачки", amount: "2 шт", magnumSearch: "кабачки" },
      { name: "Помидоры", amount: "3 шт", magnumSearch: "помидоры" },
      { name: "Лимон", amount: "1 шт", magnumSearch: "лимон" },
      { name: "Оливковое масло", amount: "30 мл", magnumSearch: "оливковое масло" },
      { name: "Укроп", amount: "пучок", magnumSearch: "укроп" },
      { name: "Соль", amount: "по вкусу", magnumSearch: "соль" },
    ],
    steps: [
      "Выложить рыбу на противень с овощами",
      "Сбрызнуть оливковым маслом и лимоном",
      "Посолить, добавить укроп",
      "Запекать при 180°C 30-35 минут",
    ],
  },
  {
    id: "lagman",
    name: "Лагман",
    description: "Густой суп с лапшой и мясом — согревающее блюдо",
    categories: ["kazakh", "family-favorites", "indulge"],
    diets: ["none"],
    prepTime: 25,
    cookTime: 60,
    servings: 5,
    calories: 450,
    familyFavorite: true,
    tags: ["суп", "лапша", "мясо"],
    ingredients: [
      { name: "Говядина", amount: "600 г", magnumSearch: "говядина" },
      { name: "Лапша лагман", amount: "400 г", magnumSearch: "лапша" },
      { name: "Картофель", amount: "3 шт", magnumSearch: "картофель" },
      { name: "Морковь", amount: "2 шт", magnumSearch: "морковь" },
      { name: "Перец болгарский", amount: "2 шт", magnumSearch: "перец болгарский" },
      { name: "Лук репчатый", amount: "2 шт", magnumSearch: "лук" },
      { name: "Чеснок", amount: "4 зубчика", magnumSearch: "чеснок" },
      { name: "Томатная паста", amount: "2 ст.л.", magnumSearch: "томатная паста" },
    ],
    steps: [
      "Обжарить мясо до золотистой корочки",
      "Добавить овощи, тушить 20 минут",
      "Добавить воду, томатную пасту, варить 30 минут",
      "Отварить лапшу отдельно",
      "Подавать суп с лапшой",
    ],
  },
  {
    id: "pancakes",
    name: "Блины с начинкой",
    description: "Блины на завтрак или ужин — дети обожают!",
    categories: ["kids", "quick", "indulge"],
    diets: ["none", "vegetarian"],
    prepTime: 10,
    cookTime: 30,
    servings: 5,
    calories: 350,
    tags: ["дети", "быстро", "сладкое"],
    ingredients: [
      { name: "Молоко", amount: "500 мл", magnumSearch: "молоко" },
      { name: "Мука", amount: "300 г", magnumSearch: "мука" },
      { name: "Яйца", amount: "3 шт", magnumSearch: "яйца" },
      { name: "Сахар", amount: "2 ст.л.", magnumSearch: "сахар" },
      { name: "Масло растительное", amount: "30 мл", magnumSearch: "масло растительное" },
      { name: "Творог", amount: "300 г", magnumSearch: "творог" },
      { name: "Сметана", amount: "200 г", magnumSearch: "сметана" },
    ],
    steps: [
      "Смешать молоко, муку, яйца и сugar",
      "Жарить блины на сковороде",
      "Начинить творогом или сметаной",
      "Подавать горячими",
    ],
  },
  {
    id: "manti",
    name: "Манты с мясом",
    description: "Паровые манты — традиция казахской кухни",
    categories: ["kazakh", "family-favorites"],
    diets: ["none"],
    prepTime: 45,
    cookTime: 40,
    servings: 5,
    calories: 400,
    familyFavorite: true,
    tags: ["мясо", "пар", "традиция"],
    ingredients: [
      { name: "Говяжий фарш", amount: "600 г", magnumSearch: "говяжий фарш" },
      { name: "Лук репчатый", amount: "3 шт", magnumSearch: "лук" },
      { name: "Мука", amount: "400 г", magnumSearch: "мука" },
      { name: "Яйцо", amount: "1 шт", magnumSearch: "яйца" },
      { name: "Картофель", amount: "2 шт", magnumSearch: "картофель" },
      { name: "Тыква", amount: "200 г", magnumSearch: "тыква" },
      { name: "Соль", amount: "по вкусу", magnumSearch: "соль" },
      { name: "Перец", amount: "по вкусу", magnumSearch: "перец" },
    ],
    steps: [
      "Замесить тесто, дать отдохнуть 30 минут",
      "Смешать фарш с луком, картофелем и тыквой",
      "Раскатать тесто, нарезать квадраты",
      "Начинить и злепить манты",
      "Готовить на пару 35-40 минут",
    ],
  },
  {
    id: "chicken-soup",
    name: "Куриный суп с лапшой",
    description: "Домашний суп — когда кто-то заболел или просто хочется тепла",
    categories: ["kids", "healthy", "quick"],
    diets: ["none", "gluten-free"],
    prepTime: 15,
    cookTime: 40,
    servings: 5,
    calories: 220,
    tags: ["суп", "курица", "дети"],
    ingredients: [
      { name: "Курица", amount: "800 г", magnumSearch: "курица" },
      { name: "Лапша", amount: "200 г", magnumSearch: "лапша" },
      { name: "Морковь", amount: "2 шт", magnumSearch: "морковь" },
      { name: "Картофель", amount: "3 шт", magnumSearch: "картофель" },
      { name: "Лук репчатый", amount: "1 шт", magnumSearch: "лук" },
      { name: "Укроп", amount: "пучок", magnumSearch: "укроп" },
      { name: "Соль", amount: "по вкусу", magnumSearch: "соль" },
    ],
    steps: [
      "Сварить куриный бульон 30 минут",
      "Добавить нарезанные овощи",
      "Варить 10 минут, добавить лапшу",
      "Варить ещё 5 минут, добавить укроп",
    ],
  },
  {
    id: "steak-potato",
    name: "Стейк с картофелем",
    description: "Сытный ужин для всей семьи — особенно для Станислава",
    categories: ["indulge", "family-favorites"],
    diets: ["none", "keto", "low-carb", "gluten-free"],
    prepTime: 10,
    cookTime: 30,
    servings: 5,
    calories: 550,
    tags: ["мясо", "стейк", "выходные"],
    ingredients: [
      { name: "Говядина стейк", amount: "1 кг", magnumSearch: "стейк говядина" },
      { name: "Картофель", amount: "1 кг", magnumSearch: "картофель" },
      { name: "Масло сливочное", amount: "50 г", magnumSearch: "масло сливочное" },
      { name: "Чеснок", amount: "3 зубчика", magnumSearch: "чеснок" },
      { name: "Розмарин", amount: "2 веточки", magnumSearch: "розмарин" },
      { name: "Соль", amount: "по вкусу", magnumSearch: "соль" },
      { name: "Перец", amount: "по вкусу", magnumSearch: "перец" },
    ],
    steps: [
      "Разогреть сковороду до максимума",
      "Обжарить стейки по 3-4 минуты с каждой стороны",
      "Добавить масло, чеснок и розмарин",
      "Запечь картофель при 200°C 25 минут",
      "Дать стейку отдохнуть 5 минут перед подачей",
    ],
  },
  {
    id: "vegetable-stew",
    name: "Овощное рагу",
    description: "Лёгкое вегетарианское блюдо с сезонными овощами",
    categories: ["healthy", "low-cal"],
    diets: ["vegetarian", "gluten-free", "low-carb"],
    prepTime: 15,
    cookTime: 35,
    servings: 5,
    calories: 180,
    tags: ["овощи", "лёгкое", "лето"],
    ingredients: [
      { name: "Кабачки", amount: "2 шт", magnumSearch: "кабачки" },
      { name: "Баклажаны", amount: "2 шт", magnumSearch: "баклажаны" },
      { name: "Помидоры", amount: "4 шт", magnumSearch: "помидоры" },
      { name: "Перец болгарский", amount: "2 шт", magnumSearch: "перец болгарский" },
      { name: "Лук репчатый", amount: "1 шт", magnumSearch: "лук" },
      { name: "Чеснок", amount: "3 зубчика", magnumSearch: "чеснок" },
      { name: "Оливковое масло", amount: "40 мл", magnumSearch: "оливковое масло" },
    ],
    steps: [
      "Нарезать все овощи кубиками",
      "Обжарить лук и чеснок",
      "Добавить овощи по очереди, тушить 30 минут",
      "Подавать горячим или холодным",
    ],
  },
  {
    id: "shashlik",
    name: "Шашлык домашний",
    description: "Шашлык на сковороде-гриль — когда нет возможности на природу",
    categories: ["indulge", "kazakh", "family-favorites"],
    diets: ["none", "gluten-free", "keto", "low-carb"],
    prepTime: 120,
    cookTime: 20,
    servings: 5,
    calories: 480,
    familyFavorite: true,
    tags: ["мясо", "гриль", "выходные"],
    ingredients: [
      { name: "Баранина", amount: "1.2 кг", magnumSearch: "баранина" },
      { name: "Лук репчатый", amount: "3 шт", magnumSearch: "лук" },
      { name: "Лимон", amount: "2 шт", magnumSearch: "лимон" },
      { name: "Масло растительное", amount: "50 мл", magnumSearch: "масло растительное" },
      { name: "Зира", amount: "1 ч.л.", magnumSearch: "зира" },
      { name: "Соль", amount: "по вкусу", magnumSearch: "соль" },
      { name: "Лаваш", amount: "3 шт", magnumSearch: "лаваш" },
    ],
    steps: [
      "Мариновать мясо с луком, лимоном и специями 2 часа",
      "Нанизать на шампуры или жарить на гриле",
      "Жарить 15-20 минут, переворачивая",
      "Подавать с лавашом и овощами",
    ],
  },
  {
    id: "mac-cheese",
    name: "Мак-энд-чиз",
    description: "Сырные макароны — любимое блюдо Данила",
    categories: ["kids", "quick", "indulge"],
    diets: ["none", "vegetarian"],
    prepTime: 10,
    cookTime: 20,
    servings: 5,
    calories: 450,
    tags: ["дети", "сыр", "быстро"],
    ingredients: [
      { name: "Макароны", amount: "500 г", magnumSearch: "макароны" },
      { name: "Сыр чеддер", amount: "300 г", magnumSearch: "cheddar" },
      { name: "Молоко", amount: "300 мл", magnumSearch: "молоко" },
      { name: "Масло сливочное", amount: "50 г", magnumSearch: "масло сливочное" },
      { name: "Мука", amount: "2 ст.л.", magnumSearch: "мука" },
      { name: "Соль", amount: "по вкусу", magnumSearch: "соль" },
    ],
    steps: [
      "Отварить макароны",
      "Приготовить соус: растопить масло, добавить муку, молоко и сыр",
      "Смешать макароны с сырным соусом",
      "Можно запечь с дополнительным сыром сверху",
    ],
  },
  {
    id: "syrniki",
    name: "Сырники",
    description: "Нежные сырники — завтрак или ужин для всей семьи",
    categories: ["kids", "quick", "family-favorites"],
    diets: ["none", "vegetarian"],
    prepTime: 10,
    cookTime: 20,
    servings: 5,
    calories: 320,
    familyFavorite: true,
    tags: ["творог", "дети", "быстро"],
    ingredients: [
      { name: "Творог", amount: "500 г", magnumSearch: "творог" },
      { name: "Яйца", amount: "2 шт", magnumSearch: "яйца" },
      { name: "Мука", amount: "100 г", magnumSearch: "мука" },
      { name: "Сахар", amount: "3 ст.л.", magnumSearch: "сахар" },
      { name: "Масло растительное", amount: "30 мл", magnumSearch: "масло растительное" },
      { name: "Сметана", amount: "150 г", magnumSearch: "сметана" },
    ],
    steps: [
      "Смешать творог, яйца, муку и сugar",
      "Сформировать сырники",
      "Жарить на сковороде до золотистой корочки",
      "Подавать со сметаной",
    ],
  },
  {
    id: "borscht",
    name: "Борщ украинский",
    description: "Классический борщ — сытный и ароматный",
    categories: ["family-favorites", "healthy"],
    diets: ["none", "gluten-free"],
    prepTime: 20,
    cookTime: 60,
    servings: 5,
    calories: 280,
    tags: ["суп", "овощи", "традиция"],
    ingredients: [
      { name: "Говядина", amount: "500 г", magnumSearch: "говядина" },
      { name: "Свёкла", amount: "2 шт", magnumSearch: "свекла" },
      { name: "Капуста", amount: "300 г", magnumSearch: "капуста" },
      { name: "Картофель", amount: "3 шт", magnumSearch: "картофель" },
      { name: "Морковь", amount: "1 шт", magnumSearch: "морковь" },
      { name: "Лук репчатый", amount: "1 шт", magnumSearch: "лук" },
      { name: "Томатная паста", amount: "2 ст.л.", magnumSearch: "томатная паста" },
      { name: "Сметана", amount: "150 г", magnumSearch: "сметана" },
    ],
    steps: [
      "Сварить мясной бульон",
      "Добавить нарезанные овощи по очереди",
      "Тушить 40 минут",
      "Подавать со сметаной и зеленью",
    ],
  },
  {
    id: "caesar-salad",
    name: "Салат Цезарь с курицей",
    description: "Классический Цезарь — быстро и вкусно",
    categories: ["quick", "low-cal", "healthy"],
    diets: ["none", "low-carb"],
    prepTime: 15,
    cookTime: 10,
    servings: 5,
    calories: 320,
    tags: ["салат", "курица", "быстро"],
    ingredients: [
      { name: "Куриное филе", amount: "500 г", magnumSearch: "куриное филе" },
      { name: "Салат айсберг", amount: "1 кочан", magnumSearch: "салат" },
      { name: "Сухари", amount: "100 г", magnumSearch: "сухари" },
      { name: "Parmesan", amount: "80 г", magnumSearch: "parmesan" },
      { name: "Яйца", amount: "2 шт", magnumSearch: "яйца" },
      { name: "Майонез", amount: "100 г", magnumSearch: "майонез" },
      { name: "Чеснок", amount: "1 зубчик", magnumSearch: "чеснок" },
    ],
    steps: [
      "Обжарить куриное филе, нарезать",
      "Порвать салат, добавить курицу",
      "Приготовить заправку из майонеза, чеснока и пармезана",
      "Добавить сухари и подавать",
    ],
  },
  {
    id: "dumplings-fried",
    name: "Жареные пельмени",
    description: "Хрустящие пельмени — быстрый ужин когда нет времени",
    categories: ["quick", "kids", "indulge"],
    diets: ["none"],
    prepTime: 5,
    cookTime: 15,
    servings: 5,
    calories: 400,
    tags: ["быстро", "дети", "заморозка"],
    ingredients: [
      { name: "Пельмени замороженные", amount: "1 кг", magnumSearch: "пельмени" },
      { name: "Масло растительное", amount: "50 мл", magnumSearch: "масло растительное" },
      { name: "Сметана", amount: "200 г", magnumSearch: "сметана" },
      { name: "Укроп", amount: "пучок", magnumSearch: "укроп" },
    ],
    steps: [
      "Разогреть сковороду с маслом",
      "Выложить замороженные пельмени",
      "Жарить до золотистой корочки с двух сторон",
      "Подавать со сметаной и укропом",
    ],
  },
  {
    id: "kazy",
    name: "Казы с гarnиром",
    description: "Традиционная казахская колбаса с гарниром",
    categories: ["kazakh", "family-favorites"],
    diets: ["none", "keto", "low-carb", "gluten-free"],
    prepTime: 10,
    cookTime: 30,
    servings: 5,
    calories: 420,
    tags: ["мясо", "традиция", "колбаса"],
    ingredients: [
      { name: "Казы", amount: "600 г", magnumSearch: "казы" },
      { name: "Картофель", amount: "800 г", magnumSearch: "картофель" },
      { name: "Лук репчатый", amount: "2 шт", magnumSearch: "лук" },
      { name: "Масло растительное", amount: "30 мл", magnumSearch: "масло растительное" },
      { name: "Соль", amount: "по вкусу", magnumSearch: "соль" },
      { name: "Перец", amount: "по вкусу", magnumSearch: "перец" },
    ],
    steps: [
      "Отварить казы 20 минут",
      "Нарезать и обжарить с луком",
      "Приготовить картофельное пюре или отварной картофель",
      "Подавать казы с гарниром",
    ],
  },
];

export function getRecipeById(id: string): Recipe | undefined {
  return RECIPES.find((r) => r.id === id);
}

export function filterRecipes(
  categories: string[],
  diet: string
): Recipe[] {
  return RECIPES.filter((recipe) => {
    const dietMatch =
      diet === "none" ||
      recipe.diets.includes(diet as Recipe["diets"][number]);

    const categoryMatch =
      categories.length === 0 ||
      categories.some((cat) => recipe.categories.includes(cat as Recipe["categories"][number]));

    return dietMatch && categoryMatch;
  });
}
