import type { Recipe, MealType } from "./types";

export const RECIPES: Recipe[] = [
  // ── ЗАВТРАКИ ──
  {
    id: "syrniki",
    name: "Сырники",
    description: "Нежные сырники со сметаной — классика русского завтрака",
    categories: ["kids", "quick", "family-favorites", "russian"],
    mealTypes: ["breakfast"],
    diets: ["none", "vegetarian"],
    prepTime: 10,
    cookTime: 20,
    servings: 5,
    calories: 320,
    familyFavorite: true,
    tags: ["творог", "дети", "быстро"],
    ingredients: [
      { name: "Творог", amount: "500 г", magnumSearch: "творог" },
      { name: "Яйца", amount: "2 шт", magnumSearch: "яйца" },
      { name: "Мука", amount: "100 г", magnumSearch: "мука" },
      { name: "Сахар", amount: "3 ст.л.", magnumSearch: "сахар" },
      { name: "Масло растительное", amount: "30 мл", magnumSearch: "масло растительное" },
      { name: "Сметана", amount: "150 г", magnumSearch: "сметана" },
    ],
    steps: [
      "Смешать творог, яйца, муку и сахар",
      "Сформировать сырники",
      "Жарить на сковороде до золотистой корочки",
      "Подавать со сметаной",
    ],
  },
  {
    id: "pancakes",
    name: "Блины",
    description: "Тонкие блины с начинкой — дети обожают!",
    categories: ["kids", "quick", "russian"],
    mealTypes: ["breakfast"],
    diets: ["none", "vegetarian"],
    prepTime: 10,
    cookTime: 30,
    servings: 5,
    calories: 350,
    tags: ["дети", "быстро"],
    ingredients: [
      { name: "Молоко", amount: "500 мл", magnumSearch: "молоко" },
      { name: "Мука", amount: "300 г", magnumSearch: "мука" },
      { name: "Яйца", amount: "3 шт", magnumSearch: "яйца" },
      { name: "Сахар", amount: "2 ст.л.", magnumSearch: "сахар" },
      { name: "Масло растительное", amount: "30 мл", magnumSearch: "масло растительное" },
      { name: "Сметана", amount: "200 г", magnumSearch: "сметана" },
    ],
    steps: [
      "Смешать молоко, муку, яйца и сахар",
      "Жарить блины на сковороде",
      "Подавать со сметаной или вареньем",
    ],
  },
  {
    id: "omlet",
    name: "Омлет с сыром",
    description: "Пышный омлет на сковороде — быстрый завтрак для всей семьи",
    categories: ["quick", "kids"],
    mealTypes: ["breakfast"],
    diets: ["none", "vegetarian", "keto", "low-carb"],
    prepTime: 5,
    cookTime: 10,
    servings: 5,
    calories: 220,
    tags: ["яйца", "быстро"],
    ingredients: [
      { name: "Яйца", amount: "8 шт", magnumSearch: "яйца" },
      { name: "Молоко", amount: "100 мл", magnumSearch: "молоко" },
      { name: "Сыр", amount: "150 г", magnumSearch: "сыр" },
      { name: "Масло сливочное", amount: "30 г", magnumSearch: "масло сливочное" },
      { name: "Соль", amount: "по вкусу", magnumSearch: "соль" },
    ],
    steps: [
      "Взбить яйца с молоком и солью",
      "Разогреть сковороду с маслом",
      "Вылить смесь, добавить тертый сыр",
      "Готовить на среднем огне под крышкой 8-10 минут",
    ],
  },
  {
    id: "kasha-manna",
    name: "Манная каша",
    description: "Нежная манка с маслом — любимый завтрак Леры",
    categories: ["kids", "quick", "russian"],
    mealTypes: ["breakfast"],
    diets: ["none", "vegetarian"],
    prepTime: 2,
    cookTime: 10,
    servings: 5,
    calories: 180,
    tags: ["каша", "дети"],
    ingredients: [
      { name: "Молоко", amount: "1 л", magnumSearch: "молоко" },
      { name: "Манная крупа", amount: "150 г", magnumSearch: "манка" },
      { name: "Сахар", amount: "3 ст.л.", magnumSearch: "сахар" },
      { name: "Масло сливочное", amount: "50 г", magnumSearch: "масло сливочное" },
    ],
    steps: [
      "Довести молоко до кипения",
      "Тонкой струйкой всыпать манку, помешивая",
      "Варить 5 минут, добавить сахар и масло",
    ],
  },
  {
    id: "tvorozhnaya-zapekanka",
    name: "Творожная запеканка",
    description: "Нежная запеканка из духовки — сытный завтрак",
    categories: ["kids", "family-favorites", "russian"],
    mealTypes: ["breakfast"],
    diets: ["none", "vegetarian"],
    prepTime: 15,
    cookTime: 40,
    servings: 5,
    calories: 290,
    familyFavorite: true,
    tags: ["творог", "духовка"],
    ingredients: [
      { name: "Творог", amount: "600 г", magnumSearch: "творог" },
      { name: "Яйца", amount: "3 шт", magnumSearch: "яйца" },
      { name: "Манная крупа", amount: "80 г", magnumSearch: "манка" },
      { name: "Сахар", amount: "100 г", magnumSearch: "сахар" },
      { name: "Изюм", amount: "100 г", magnumSearch: "изюм" },
      { name: "Сметана", amount: "150 г", magnumSearch: "сметана" },
    ],
    steps: [
      "Смешать творог, яйца, манку и сахар",
      "Добавить изюм, выложить в форму",
      "Запекать при 180°C 35-40 минут",
      "Подавать со сметаной",
    ],
  },
  {
    id: "grechka-milk",
    name: "Гречка на молоке",
    description: "Сладкая гречневая каша — питательный завтрак",
    categories: ["healthy", "russian", "kids"],
    mealTypes: ["breakfast"],
    diets: ["none", "vegetarian", "gluten-free"],
    prepTime: 5,
    cookTime: 20,
    servings: 5,
    calories: 200,
    tags: ["каша", "гречка"],
    ingredients: [
      { name: "Гречка", amount: "300 г", magnumSearch: "гречка" },
      { name: "Молоко", amount: "800 мл", magnumSearch: "молоко" },
      { name: "Сахар", amount: "3 ст.л.", magnumSearch: "сахар" },
      { name: "Масло сливочное", amount: "40 г", magnumSearch: "масло сливочное" },
    ],
    steps: [
      "Отварить гречку до полуготовности",
      "Залить молоком, добавить сахар",
      "Томить 10 минут, добавить масло",
    ],
  },

  // ── ОБЕДЫ ──
  {
    id: "borscht",
    name: "Борщ",
    description: "Классический русский борщ со сметаной",
    categories: ["family-favorites", "healthy", "russian"],
    mealTypes: ["lunch", "dinner"],
    diets: ["none", "gluten-free"],
    prepTime: 20,
    cookTime: 60,
    servings: 5,
    calories: 280,
    familyFavorite: true,
    tags: ["суп", "овощи"],
    ingredients: [
      { name: "Говядина", amount: "500 г", magnumSearch: "говядина" },
      { name: "Свёкла", amount: "2 шт", magnumSearch: "свекла" },
      { name: "Капуста", amount: "300 г", magnumSearch: "капуста" },
      { name: "Картофель", amount: "3 шт", magnumSearch: "картофель" },
      { name: "Морковь", amount: "1 шт", magnumSearch: "морковь" },
      { name: "Лук репчатый", amount: "1 шт", magnumSearch: "лук" },
      { name: "Томатная паста", amount: "2 ст.л.", magnumSearch: "томатная паста" },
      { name: "Сметана", amount: "150 г", magnumSearch: "сметана" },
    ],
    steps: [
      "Сварить мясной бульон",
      "Добавить нарезанные овощи по очереди",
      "Тушить 40 минут",
      "Подавать со сметаной",
    ],
  },
  {
    id: "chicken-soup",
    name: "Куриный суп с лапшой",
    description: "Домашний суп — когда хочется тепла",
    categories: ["kids", "healthy", "quick", "russian"],
    mealTypes: ["lunch"],
    diets: ["none", "gluten-free"],
    prepTime: 15,
    cookTime: 40,
    servings: 5,
    calories: 220,
    tags: ["суп", "курица"],
    ingredients: [
      { name: "Курица", amount: "800 г", magnumSearch: "курица" },
      { name: "Лапша", amount: "200 г", magnumSearch: "лапша" },
      { name: "Морковь", amount: "2 шт", magnumSearch: "морковь" },
      { name: "Картофель", amount: "3 шт", magnumSearch: "картофель" },
      { name: "Лук репчатый", amount: "1 шт", magnumSearch: "лук" },
      { name: "Укроп", amount: "пучок", magnumSearch: "укроп" },
      { name: "Соль", amount: "по вкусу", magnumSearch: "соль" },
    ],
    steps: [
      "Сварить куриный бульон 30 минут",
      "Добавить нарезанные овощи",
      "Варить 10 минут, добавить лапшу",
      "Варить ещё 5 минут, добавить укроп",
    ],
  },
  {
    id: "shchi",
    name: "Щи из свежей капусты",
    description: "Ароматные щи — классика русской кухни",
    categories: ["russian", "family-favorites", "healthy"],
    mealTypes: ["lunch"],
    diets: ["none", "gluten-free"],
    prepTime: 15,
    cookTime: 50,
    servings: 5,
    calories: 240,
    familyFavorite: true,
    tags: ["суп", "капуста"],
    ingredients: [
      { name: "Говядина", amount: "400 г", magnumSearch: "говядина" },
      { name: "Капуста", amount: "500 г", magnumSearch: "капуста" },
      { name: "Картофель", amount: "3 шт", magnumSearch: "картофель" },
      { name: "Морковь", amount: "1 шт", magnumSearch: "морковь" },
      { name: "Лук репчатый", amount: "1 шт", magnumSearch: "лук" },
      { name: "Томатная паста", amount: "1 ст.л.", magnumSearch: "томатная паста" },
      { name: "Сметана", amount: "150 г", magnumSearch: "сметана" },
    ],
    steps: [
      "Сварить мясной бульон",
      "Добавить картофель и капусту",
      "Обжарить лук с морковью, добавить в суп",
      "Варить 30 минут, подавать со сметаной",
    ],
  },
  {
    id: "rassolnik",
    name: "Рассольник",
    description: "Суп с солёными огурцами — согревающий обед",
    categories: ["russian", "family-favorites"],
    mealTypes: ["lunch"],
    diets: ["none", "gluten-free"],
    prepTime: 15,
    cookTime: 45,
    servings: 5,
    calories: 260,
    tags: ["суп", "огурцы"],
    ingredients: [
      { name: "Говядина", amount: "400 г", magnumSearch: "говядина" },
      { name: "Перловка", amount: "100 г", magnumSearch: "перловка" },
      { name: "Картофель", amount: "3 шт", magnumSearch: "картофель" },
      { name: "Морковь", amount: "1 шт", magnumSearch: "морковь" },
      { name: "Огурцы солёные", amount: "3 шт", magnumSearch: "огурцы маринованные" },
      { name: "Лук репчатый", amount: "1 шт", magnumSearch: "лук" },
      { name: "Сметана", amount: "150 г", magnumSearch: "сметана" },
    ],
    steps: [
      "Сварить мясо с перловкой",
      "Добавить картофель и морковь",
      "Нарезать огурцы, добавить в суп",
      "Варить 15 минут, подавать со сметаной",
    ],
  },
  {
    id: "solyanka",
    name: "Солянка мясная",
    description: "Наваристая солянка — сытный обед",
    categories: ["russian", "indulge", "family-favorites"],
    mealTypes: ["lunch"],
    diets: ["none", "gluten-free", "low-carb"],
    prepTime: 20,
    cookTime: 40,
    servings: 5,
    calories: 320,
    tags: ["суп", "мясо"],
    ingredients: [
      { name: "Колбаса", amount: "200 г", magnumSearch: "колбаса" },
      { name: "Ветчина", amount: "150 г", magnumSearch: "ветчина" },
      { name: "Говядина", amount: "300 г", magnumSearch: "говядина" },
      { name: "Огурцы солёные", amount: "2 шт", magnumSearch: "огурцы маринованные" },
      { name: "Маслины", amount: "50 г", magnumSearch: "маслины" },
      { name: "Лимон", amount: "1 шт", magnumSearch: "лимон" },
      { name: "Томатная паста", amount: "2 ст.л.", magnumSearch: "томатная паста" },
      { name: "Сметана", amount: "100 г", magnumSearch: "сметана" },
    ],
    steps: [
      "Сварить бульон из говядины",
      "Нарезать колбасу и ветчину, добавить в суп",
      "Добавить огурцы, маслины и томатную пасту",
      "Подавать с лимоном и сметаной",
    ],
  },
  {
    id: "greek-salad",
    name: "Греческий салат",
    description: "Свежий лёгкий салат — идеален на обед",
    categories: ["healthy", "low-cal", "quick"],
    mealTypes: ["lunch"],
    diets: ["vegetarian", "gluten-free", "keto", "low-carb"],
    prepTime: 15,
    cookTime: 0,
    servings: 5,
    calories: 180,
    tags: ["салат", "лёгкое"],
    ingredients: [
      { name: "Помидоры", amount: "4 шт", magnumSearch: "помидоры" },
      { name: "Огурцы", amount: "3 шт", magnumSearch: "огурцы" },
      { name: "Болгарский перец", amount: "2 шт", magnumSearch: "перец болгарский" },
      { name: "Сыр фета", amount: "200 г", magnumSearch: "фета" },
      { name: "Маслины", amount: "100 г", magnumSearch: "маслины" },
      { name: "Оливковое масло", amount: "50 мл", magnumSearch: "оливковое масло" },
    ],
    steps: [
      "Нарезать овощи крупными кубиками",
      "Добавить фету и маслины",
      "Заправить оливковым маслом",
    ],
  },
  {
    id: "caesar-salad",
    name: "Салат Цезарь с курицей",
    description: "Сытный салат — быстрый обед",
    categories: ["quick", "low-cal", "healthy"],
    mealTypes: ["lunch"],
    diets: ["none", "low-carb"],
    prepTime: 15,
    cookTime: 10,
    servings: 5,
    calories: 320,
    tags: ["салат", "курица"],
    ingredients: [
      { name: "Куриное филе", amount: "500 г", magnumSearch: "куриное филе" },
      { name: "Салат", amount: "1 кочан", magnumSearch: "салат" },
      { name: "Сухари", amount: "100 г", magnumSearch: "сухари" },
      { name: "Parmesan", amount: "80 г", magnumSearch: "parmesan" },
      { name: "Майонез", amount: "100 г", magnumSearch: "майонез" },
    ],
    steps: [
      "Обжарить куриное филе на сковороде, нарезать",
      "Смешать салат с курицей и заправкой",
      "Добавить сухари и пармезан",
    ],
  },
  {
    id: "olivier",
    name: "Салат Оливье",
    description: "Классический Оливье — must have на любом столе",
    categories: ["russian", "family-favorites", "indulge"],
    mealTypes: ["lunch"],
    diets: ["none"],
    prepTime: 30,
    cookTime: 20,
    servings: 5,
    calories: 350,
    familyFavorite: true,
    tags: ["салат", "праздник"],
    ingredients: [
      { name: "Картофель", amount: "4 шт", magnumSearch: "картофель" },
      { name: "Морковь", amount: "2 шт", magnumSearch: "морковь" },
      { name: "Яйца", amount: "4 шт", magnumSearch: "яйца" },
      { name: "Колбаса", amount: "300 г", magnumSearch: "колбаса" },
      { name: "Огурцы солёные", amount: "3 шт", magnumSearch: "огурцы маринованные" },
      { name: "Горошек консервированный", amount: "1 банка", magnumSearch: "горошек" },
      { name: "Майонез", amount: "200 г", magnumSearch: "майонез" },
    ],
    steps: [
      "Отварить картофель, морковь и яйца",
      "Нарезать все ингредиенты кубиками",
      "Смешать с горошком и майонезом",
      "Охладить перед подачей",
    ],
  },
  {
    id: "dumplings-fried",
    name: "Жареные пельмени",
    description: "Хрустящие пельмени — быстрый обед",
    categories: ["quick", "kids", "russian"],
    mealTypes: ["lunch"],
    diets: ["none"],
    prepTime: 5,
    cookTime: 15,
    servings: 5,
    calories: 400,
    tags: ["быстро", "заморозка"],
    ingredients: [
      { name: "Пельмени замороженные", amount: "1 кг", magnumSearch: "пельмени" },
      { name: "Масло растительное", amount: "50 мл", magnumSearch: "масло растительное" },
      { name: "Сметана", amount: "200 г", magnumSearch: "сметана" },
    ],
    steps: [
      "Разогреть сковороду с маслом",
      "Выложить замороженные пельмени",
      "Жарить до золотистой корочки",
      "Подавать со сметаной",
    ],
  },
  {
    id: "mac-cheese",
    name: "Макароны с сыром",
    description: "Сырные макароны — любимое блюдо Данила",
    categories: ["kids", "quick", "indulge"],
    mealTypes: ["lunch"],
    diets: ["none", "vegetarian"],
    prepTime: 10,
    cookTime: 20,
    servings: 5,
    calories: 450,
    tags: ["дети", "сыр"],
    ingredients: [
      { name: "Макароны", amount: "500 г", magnumSearch: "макароны" },
      { name: "Сыр", amount: "300 г", magnumSearch: "сыр" },
      { name: "Молоко", amount: "300 мл", magnumSearch: "молоко" },
      { name: "Масло сливочное", amount: "50 г", magnumSearch: "масло сливочное" },
      { name: "Мука", amount: "2 ст.л.", magnumSearch: "мука" },
    ],
    steps: [
      "Отварить макароны",
      "Приготовить сырный соус",
      "Смешать и подавать горячим",
    ],
  },

  // ── УЖИНЫ ──
  {
    id: "plov",
    name: "Плов домашний",
    description: "Ароматный плов на сковороде — сытный ужин для всей семьи",
    categories: ["family-favorites", "russian", "indulge"],
    mealTypes: ["dinner"],
    diets: ["none", "gluten-free", "low-carb"],
    prepTime: 20,
    cookTime: 60,
    servings: 5,
    calories: 520,
    familyFavorite: true,
    tags: ["мясо", "рис"],
    ingredients: [
      { name: "Говядина", amount: "800 г", magnumSearch: "говядина" },
      { name: "Рис", amount: "500 г", magnumSearch: "рис" },
      { name: "Морковь", amount: "400 г", magnumSearch: "морковь" },
      { name: "Лук репчатый", amount: "3 шт", magnumSearch: "лук" },
      { name: "Масло растительное", amount: "100 мл", magnumSearch: "масло растительное" },
      { name: "Чеснок", amount: "1 головка", magnumSearch: "чеснок" },
      { name: "Зира", amount: "1 ч.л.", magnumSearch: "зира" },
    ],
    steps: [
      "Обжарить мясо на сковороде до золотистой корочки",
      "Добавить лук и морковь, тушить 15 минут",
      "Залить водой, добавить рис и специи",
      "Тушить под крышкой 40 минут на медленном огне",
    ],
  },
  {
    id: "pelmeni",
    name: "Пельмени домашние",
    description: "Сытные домашние пельмени — семейная классика",
    categories: ["family-favorites", "russian", "indulge"],
    mealTypes: ["dinner", "lunch"],
    diets: ["none"],
    prepTime: 60,
    cookTime: 15,
    servings: 5,
    calories: 420,
    familyFavorite: true,
    tags: ["мясо", "традиция"],
    ingredients: [
      { name: "Говяжий фарш", amount: "500 г", magnumSearch: "говяжий фарш" },
      { name: "Свиной фарш", amount: "300 г", magnumSearch: "свиной фарш" },
      { name: "Мука", amount: "400 г", magnumSearch: "мука" },
      { name: "Яйца", amount: "2 шт", magnumSearch: "яйца" },
      { name: "Лук репчатый", amount: "2 шт", magnumSearch: "лук" },
      { name: "Сметана", amount: "200 г", magnumSearch: "сметана" },
    ],
    steps: [
      "Замесить тесто, приготовить фарш",
      "Слепить пельмени",
      "Варить в подсоленной воде 7-10 минут",
      "Подавать со сметаной",
    ],
  },
  {
    id: "chicken-cutlets",
    name: "Куриные котлеты с пюре",
    description: "Нежные котлеты с картофельным пюре — хит у детей",
    categories: ["kids", "family-favorites", "quick", "russian"],
    mealTypes: ["dinner", "lunch"],
    diets: ["none", "gluten-free", "low-carb"],
    prepTime: 15,
    cookTime: 30,
    servings: 5,
    calories: 380,
    familyFavorite: true,
    tags: ["курица", "дети"],
    ingredients: [
      { name: "Куриный фарш", amount: "800 г", magnumSearch: "куриный фарш" },
      { name: "Картофель", amount: "1 кг", magnumSearch: "картофель" },
      { name: "Лук репчатый", amount: "1 шт", magnumSearch: "лук" },
      { name: "Яйцо", amount: "1 шт", magnumSearch: "яйца" },
      { name: "Молоко", amount: "200 мл", magnumSearch: "молоко" },
      { name: "Масло сливочное", amount: "50 г", magnumSearch: "масло сливочное" },
      { name: "Сухари", amount: "100 г", magnumSearch: "сухари" },
    ],
    steps: [
      "Сформировать котлеты, обжарить на сковороде",
      "Сварить картофель, размять с маслом и молоком",
      "Подавать котлеты с пюре",
    ],
  },
  {
    id: "golubtsy",
    name: "Голубцы",
    description: "Фарш в капустных листьях — домашний русский ужин",
    categories: ["russian", "family-favorites"],
    mealTypes: ["dinner"],
    diets: ["none", "gluten-free", "low-carb"],
    prepTime: 30,
    cookTime: 60,
    servings: 5,
    calories: 350,
    familyFavorite: true,
    tags: ["мясо", "капуста"],
    ingredients: [
      { name: "Говяжий фарш", amount: "600 г", magnumSearch: "говяжий фарш" },
      { name: "Капуста", amount: "1 кочан", magnumSearch: "капуста" },
      { name: "Рис", amount: "150 г", magnumSearch: "рис" },
      { name: "Морковь", amount: "1 шт", magnumSearch: "морковь" },
      { name: "Лук репчатый", amount: "2 шт", magnumSearch: "лук" },
      { name: "Томатная паста", amount: "2 ст.л.", magnumSearch: "томатная паста" },
      { name: "Сметана", amount: "150 г", magnumSearch: "сметана" },
    ],
    steps: [
      "Отварить капусту, отделить листья",
      "Смешать фарш с рисом и луком",
      "Завернуть фарш в листья",
      "Тушить с томатной пастой 50 минут",
      "Подавать со сметаной",
    ],
  },
  {
    id: "vareniki",
    name: "Вареники с картошкой",
    description: "Домашние вареники — простой и сытный ужин",
    categories: ["russian", "family-favorites", "kids"],
    mealTypes: ["dinner"],
    diets: ["none", "vegetarian"],
    prepTime: 40,
    cookTime: 15,
    servings: 5,
    calories: 360,
    tags: ["тесто", "картофель"],
    ingredients: [
      { name: "Мука", amount: "500 г", magnumSearch: "мука" },
      { name: "Яйца", amount: "2 шт", magnumSearch: "яйца" },
      { name: "Картофель", amount: "800 г", magnumSearch: "картофель" },
      { name: "Лук репчатый", amount: "2 шт", magnumSearch: "лук" },
      { name: "Масло сливочное", amount: "80 г", magnumSearch: "масло сливочное" },
      { name: "Сметана", amount: "200 г", magnumSearch: "сметана" },
    ],
    steps: [
      "Замесить тесто, приготовить начинку из картофеля",
      "Слепить вареники",
      "Варить 5-7 минут после всплытия",
      "Подавать с маслом и сметаной",
    ],
  },
  {
    id: "zharkoe",
    name: "Жаркое в горшочках",
    description: "Мясо с овощами в духовке — ароматный семейный ужин",
    categories: ["russian", "family-favorites", "indulge"],
    mealTypes: ["dinner"],
    diets: ["none", "gluten-free", "low-carb"],
    prepTime: 20,
    cookTime: 90,
    servings: 5,
    calories: 420,
    familyFavorite: true,
    tags: ["мясо", "духовка"],
    ingredients: [
      { name: "Свинина", amount: "800 г", magnumSearch: "свинина" },
      { name: "Картофель", amount: "800 г", magnumSearch: "картофель" },
      { name: "Морковь", amount: "2 шт", magnumSearch: "морковь" },
      { name: "Лук репчатый", amount: "2 шт", magnumSearch: "лук" },
      { name: "Чеснок", amount: "4 зубчика", magnumSearch: "чеснок" },
      { name: "Томатная паста", amount: "2 ст.л.", magnumSearch: "томатная паста" },
    ],
    steps: [
      "Нарезать мясо и овощи",
      "Выложить в горшочки слоями",
      "Добавить томатную пасту и немного воды",
      "Запекать при 180°C 1.5 часа",
    ],
  },
  {
    id: "grechka-kotleti",
    name: "Гречка с котлетами",
    description: "Классика русской кухни — гречка с домашними котлетами",
    categories: ["russian", "family-favorites", "kids"],
    mealTypes: ["dinner"],
    diets: ["none", "gluten-free"],
    prepTime: 15,
    cookTime: 30,
    servings: 5,
    calories: 400,
    familyFavorite: true,
    tags: ["гречка", "котлеты"],
    ingredients: [
      { name: "Говяжий фарш", amount: "700 г", magnumSearch: "говяжий фарш" },
      { name: "Гречка", amount: "400 г", magnumSearch: "гречка" },
      { name: "Лук репчатый", amount: "2 шт", magnumSearch: "лук" },
      { name: "Яйцо", amount: "1 шт", magnumSearch: "яйца" },
      { name: "Масло сливочное", amount: "40 г", magnumSearch: "масло сливочное" },
    ],
    steps: [
      "Отварить гречку с маслом",
      "Сформировать котлеты из фарша с луком",
      "Обжарить котлеты на сковороде",
      "Подавать с гречкой",
    ],
  },
  {
    id: "pasta-carbonara",
    name: "Паста Карбонара",
    description: "Быстрая и сытная паста — хит у Славы",
    categories: ["quick", "indulge"],
    mealTypes: ["dinner"],
    diets: ["none"],
    prepTime: 10,
    cookTime: 15,
    servings: 5,
    calories: 480,
    tags: ["паста", "быстро"],
    ingredients: [
      { name: "Спагетти", amount: "500 г", magnumSearch: "спагетти" },
      { name: "Бекон", amount: "200 г", magnumSearch: "бекон" },
      { name: "Яйца", amount: "4 шт", magnumSearch: "яйца" },
      { name: "Parmesan", amount: "100 г", magnumSearch: "parmesan" },
      { name: "Чеснок", amount: "2 зубчика", magnumSearch: "чеснок" },
    ],
    steps: [
      "Отварить спагетти",
      "Обжарить бекон на сковороде",
      "Смешать с яично-сырной смесью",
      "Подавать сразу",
    ],
  },
  {
    id: "fish-baked",
    name: "Запечённая рыба с овощами",
    description: "Полезный ужин из духовки",
    categories: ["healthy", "low-cal"],
    mealTypes: ["dinner"],
    diets: ["none", "gluten-free", "keto", "low-carb"],
    prepTime: 15,
    cookTime: 35,
    servings: 5,
    calories: 280,
    tags: ["рыба", "духовка"],
    ingredients: [
      { name: "Филе судака", amount: "800 г", magnumSearch: "судак" },
      { name: "Кабачки", amount: "2 шт", magnumSearch: "кабачки" },
      { name: "Помидоры", amount: "3 шт", magnumSearch: "помидоры" },
      { name: "Лимон", amount: "1 шт", magnumSearch: "лимон" },
      { name: "Оливковое масло", amount: "30 мл", magnumSearch: "оливковое масло" },
    ],
    steps: [
      "Выложить рыбу с овощами на противень",
      "Сбрызнуть маслом и лимоном",
      "Запекать при 180°C 30-35 минут",
    ],
  },
  {
    id: "kotleta-pozharsky",
    name: "Котлеты по-пожарски",
    description: "Сочные куриные котлеты в панировке — для всей семьи",
    categories: ["russian", "family-favorites", "indulge"],
    mealTypes: ["dinner"],
    diets: ["none"],
    prepTime: 20,
    cookTime: 25,
    servings: 5,
    calories: 440,
    tags: ["курица", "классика"],
    ingredients: [
      { name: "Куриное филе", amount: "800 г", magnumSearch: "куриное филе" },
      { name: "Масло сливочное", amount: "100 г", magnumSearch: "масло сливочное" },
      { name: "Яйца", amount: "2 шт", magnumSearch: "яйца" },
      { name: "Сухари", amount: "200 г", magnumSearch: "сухари" },
      { name: "Мука", amount: "100 г", magnumSearch: "мука" },
      { name: "Картофель", amount: "800 г", magnumSearch: "картофель" },
    ],
    steps: [
      "Отбить куриное филе, положить внутрь кусочек масла",
      "Обвалять в муке, яйце и сухарях",
      "Жарить на сковороде до золотистой корочки",
      "Подавать с картофельным пюре",
    ],
  },
  {
    id: "vegetable-stew",
    name: "Тушёные овощи",
    description: "Лёгкий овощной ужин на сковороде",
    categories: ["healthy", "low-cal"],
    mealTypes: ["dinner", "lunch"],
    diets: ["vegetarian", "gluten-free", "low-carb"],
    prepTime: 15,
    cookTime: 35,
    servings: 5,
    calories: 180,
    tags: ["овощи", "лёгкое"],
    ingredients: [
      { name: "Кабачки", amount: "2 шт", magnumSearch: "кабачки" },
      { name: "Баклажаны", amount: "2 шт", magnumSearch: "баклажаны" },
      { name: "Помидоры", amount: "4 шт", magnumSearch: "помидоры" },
      { name: "Перец болгарский", amount: "2 шт", magnumSearch: "перец болгарский" },
      { name: "Лук репчатый", amount: "1 шт", magnumSearch: "лук" },
      { name: "Масло растительное", amount: "40 мл", magnumSearch: "масло растительное" },
    ],
    steps: [
      "Нарезать овощи кубиками",
      "Тушить на сковороде 30 минут",
      "Подавать горячим",
    ],
  },
  {
    id: "beef-stroganoff",
    name: "Бефстроганов",
    description: "Нежная говядина в сливочном соусе — ужин для особого дня",
    categories: ["russian", "indulge", "family-favorites"],
    mealTypes: ["dinner"],
    diets: ["none", "low-carb"],
    prepTime: 15,
    cookTime: 30,
    servings: 5,
    calories: 480,
    tags: ["говядина", "сливки"],
    ingredients: [
      { name: "Говядина", amount: "800 г", magnumSearch: "говядина" },
      { name: "Сметана", amount: "300 г", magnumSearch: "сметана" },
      { name: "Лук репчатый", amount: "2 шт", magnumSearch: "лук" },
      { name: "Грибы", amount: "300 г", magnumSearch: "шампиньоны" },
      { name: "Мука", amount: "2 ст.л.", magnumSearch: "мука" },
      { name: "Масло сливочное", amount: "40 г", magnumSearch: "масло сливочное" },
    ],
    steps: [
      "Нарезать говядину соломкой, обжарить",
      "Добавить лук и грибы",
      "Залить сметаной, тушить 20 минут",
      "Подавать с гречкой или макaronами",
    ],
  },
];

export function getRecipeById(id: string): Recipe | undefined {
  return RECIPES.find((r) => r.id === id);
}

export function filterRecipes(
  categories: string[],
  diet: string,
  mealType?: MealType
): Recipe[] {
  return RECIPES.filter((recipe) => {
    const dietMatch =
      diet === "none" ||
      recipe.diets.includes(diet as Recipe["diets"][number]);

    const categoryMatch =
      categories.length === 0 ||
      categories.some((cat) =>
        recipe.categories.includes(cat as Recipe["categories"][number])
      );

    const mealTypeMatch = !mealType || recipe.mealTypes.includes(mealType);

    return dietMatch && categoryMatch && mealTypeMatch;
  });
}

export function getMealSlotKey(dayIndex: number, mealType: MealType): string {
  return `${dayIndex}-${mealType}`;
}
